services:
  - type: web
    name: bakery-pricing-tool
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python3 render_start.py
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
